import React from 'react';
import {useEffect,useMemo,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowLeft,CalendarDays,CheckCircle2,CreditCard,IndianRupee,WalletCards,Zap} from 'lucide-react';
import api from '../utils/api';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
export default function Payments(){
 const [searchParams]=useSearchParams(); const initialMonth=Number(searchParams.get('month')||0); const [data,setData]=useState(null),[selected,setSelected]=useState(initialMonth?[initialMonth]:[]),[method,setMethod]=useState('upi'),[extra,setExtra]=useState(''),[ahead,setAhead]=useState('0'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=()=>api.get('/dashboard').then(r=>setData(r.data));
 useEffect(()=>{load()},[]);
 const installments=useMemo(()=>data?.payments?.filter(p=>p.paymentType==='installment')||[],[data]);
 const paidCount=installments.filter(p=>p.status==='paid').length;
 const selectedRows=installments.filter(p=>selected.includes(p.month)&&p.status!=='paid');
 const total=selectedRows.reduce((s,p)=>s+p.amount,0);
 const toggle=m=>setSelected(v=>v.includes(m)?v.filter(x=>x!==m):[...v,m]);
 const paySelected=async()=>{if(!selected.length)return;setBusy(true);setMessage('');try{const r=await api.post('/payments/months',{months:selected,paymentMethod:method});setMessage(`${money(r.data.amount)} payment recorded for month(s) ${r.data.months.join(', ')}.`);setSelected([]);await load()}catch(e){setMessage(e.response?.data?.message||'Unable to process payment.')}finally{setBusy(false)}};
 const payExtra=async()=>{if(!extra)return;setBusy(true);setMessage('');try{await api.post('/payments/extra',{amount:Number(extra),monthsAhead:Number(ahead),paymentMethod:method});setMessage(`${money(extra)} extra payment recorded.`);setExtra('');await load()}catch(e){setMessage(e.response?.data?.message||'Unable to process extra payment.')}finally{setBusy(false)}};
 if(!data)return <div className="page-loader">Loading payment options…</div>;
 return <div className="payments-page"><div className="page-title"><Link to="/dashboard" className="back-link"><ArrowLeft size={16}/>Back to dashboard</Link><span className="eyebrow">SECURE PAYMENTS</span><h1>Pay your chit installment</h1><p>Choose a particular month, clear a past due month, or make an extra payment after four completed installments.</p></div>
 {message&&<div className="payment-message"><CheckCircle2 size={18}/>{message}</div>}
 <div className="payment-layout"><section className="panel payment-panel"><div className="panel-head"><div><span className="eyebrow">MONTHLY SCHEDULE</span><h2>Choose month(s) to pay</h2></div><span className="payment-count">{paidCount} paid</span></div><div className="payment-options">{installments.map(p=>{const past=p.status!=='paid'&&p.dueDate&&new Date(p.dueDate)<new Date();return <label className={`pay-row ${p.status==='paid'?'is-paid':''}`} key={p._id}><input type="checkbox" disabled={p.status==='paid'} checked={selected.includes(p.month)} onChange={()=>toggle(p.month)}/><span className="month-badge">{String(p.month).padStart(2,'0')}</span><span className="pay-info"><b>Month {p.month}</b><small>Due {p.dueDate?new Date(p.dueDate).toLocaleDateString('en-IN'):'—'}</small></span><strong>{money(p.amount)}</strong><span className={`pill ${p.status}`}>{past?'past due':p.status}</span></label>})}</div><div className="pay-total"><span>Selected total</span><strong>{money(total)}</strong></div><div className="method-grid"><label className={method==='upi'?'active':''}><input type="radio" value="upi" checked={method==='upi'} onChange={e=>setMethod(e.target.value)}/><WalletCards/>UPI</label><label className={method==='card'?'active':''}><input type="radio" value="card" checked={method==='card'} onChange={e=>setMethod(e.target.value)}/><CreditCard/>Card</label><label className={method==='netbanking'?'active':''}><input type="radio" value="netbanking" checked={method==='netbanking'} onChange={e=>setMethod(e.target.value)}/><IndianRupee/>Net Banking</label></div><button className="btn primary full" disabled={!selected.length||busy} onClick={paySelected}>{busy?'Processing…':`Pay ${money(total)} for selected month(s)`}</button><small className="payment-note">For live deployment, connect this flow to your approved payment gateway (UPI/card/net banking) before accepting real money.</small></section>
 <aside className="side-stack"><section className="panel extra-panel"><span className="eyebrow">AFTER 4 MONTHS</span><h2>Extra / advance payment</h2><p>After you complete at least 4 monthly installments, you can pay an additional amount or advance future months.</p><div className="extra-rule"><Zap size={18}/><span><b>{paidCount}/4 installments completed</b><small>{paidCount>=4?'Extra payment is unlocked.':'Complete 4 installments to unlock this option.'}</small></span></div><label className="field-label">Extra amount<input type="number" min="1" value={extra} onChange={e=>setExtra(e.target.value)} placeholder="Enter amount"/></label><label className="field-label">Advance future months (optional)<select value={ahead} onChange={e=>setAhead(e.target.value)}><option value="0">Extra payment only</option><option value="1">1 future month</option><option value="2">2 future months</option><option value="3">3 future months</option></select></label><button className="btn primary full" disabled={paidCount<4||!extra||busy} onClick={payExtra}><Zap size={16}/>Make extra payment</button></section><section className="panel payment-history"><div className="panel-head"><h3>Recent extra payments</h3></div>{data.payments.filter(p=>p.paymentType==='extra'||p.paymentType==='advance').slice(-5).reverse().map(p=><div className="history-row" key={p._id}><span>{p.paymentType==='advance'?'Advance':'Extra'}<small>{new Date(p.paidDate||p.createdAt).toLocaleDateString('en-IN')}</small></span><b>{money(p.amount)}</b></div>)}{!data.payments.some(p=>p.paymentType==='extra'||p.paymentType==='advance')&&<p className="muted">No extra payments yet.</p>}</section></aside></div></div>;
}
